landing/urls.py
from django.urls import path
from landing.views import landing_page, index_page

app_name = "landing"

urlpatterns = [
    path("", index_page, name="index"),
    path("landing/", landing_page, name="landing"),
]

story7/urls.py
from django.urls import path
from story7.views import story7_page

app_name = "story7"

urlpatterns = [
    path("", story7_page, name="story7"),
]

story8/urls.py
from django.urls import path
from story8.views import story8_page

app_name = "story8"

urlpatterns = [
    path("", story8_page, name="story8"),
]

story9/urls.py
from django.urls import path
from story9.views import story9_page, story9_login_page, story9_logout_page, story9_signup_page

app_name = "story9"

urlpatterns = [
    path("", story9_page, name="story9"),
    path("login/", story9_login_page, name="story9_login"),
    path("logout/", story9_logout_page, name="story9_logout"),
    path("signup/", story9_signup_page, name="story9_signup")
]

storypt2/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "storypt2"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("landing.urls")),
    path("story7/", include("story7.urls")),
    path("story8/", include("story8.urls")),
    path("story9/", include("story9.urls"))
]

landing/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Status(models.Model):
    status = models.TextField(max_length=300, blank=False, null=False)
    date_created = models.DateTimeField(default=datetime.now, blank=False)

story10/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

class Kegiatan(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    desc = models.TextField(max_length=2000, blank=True, null=True)

class Kepanitiaan(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    date = models.CharField(max_length=100, blank=True, null=True)
    position = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(max_length=2000, blank=True, null=True)

class Organisasi(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    date = models.CharField(max_length=100, blank=True, null=True)
    position = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(max_length=2000, blank=True, null=True)

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

landing/forms.py
from django import forms
from landing.models import Status

class Status_Form(forms.ModelForm):
    class Meta:
        model = Status
        fields = [
            'status'
        ]
    
        labels = {
            'status':'Status',
        }

        required = {
            'status':True
        }

        widgets = {
            'status':forms.Textarea(
                attrs = {
                    'id':'status-input'
                }
            )
        }

story9/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

landing/views.py
from django.shortcuts import render, redirect
from landing.models import Status
from landing.forms import Status_Form

# Create your views here.

def index_page(request):
    return redirect('/landing/')

def landing_page(request):
    form = Status_Form(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('/landing/')

    statuses = Status.objects.all()
    context = {
        'page_title':'landing',
        'status':statuses,
        'form':form,
    }
    return render(request, 'landing/landing.html', context)

story10/views.py
from django.shortcuts import render

# Create your views here.

story7/views.py
from django.shortcuts import render
from story7.models import Kegiatan, Kepanitiaan, Organisasi

# Create your views here.

def story7_page(request):
    kegiatan = Kegiatan.objects.all()
    kepanitiaan = Kepanitiaan.objects.all()
    organisasi = Organisasi.objects.all()
    context = {
        'title':'Story 7',
        'kegiatan':kegiatan,
        'kepanitiaan':kepanitiaan,
        'organisasi':organisasi,
    }
    return render(request, "story7/index.html", context)

story8/views.py
from django.shortcuts import render

# Create your views here.

def story8_page(request):
    context = {
        'title':'Story 8',
    }
    return render(request, "story8/index.html", context)

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from story9.forms import SignUpForm

# Create your views here.

def story9_page(request):
    context = {
        'title':'Story 9',
    }
    return render(request, "story9/index9.html", context)

def story9_login_page(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()

            if user is not None:
                login(request, user)
                return redirect('/story9/')
            else:
                return redirect('/story9/login/')
    else:
        form = AuthenticationForm()
        
    context = {
        'title':'Story 9 Login',
        'form':form,
    }

    return render(request, "story9/login.html", context)

def story9_logout_page(request):
    context = {
        'title':'Logout'
    }

    if request.method == "POST":
        if request.POST["logout"] == 'Logout':
            logout(request)
            return redirect("/story9/")

    return render(request, "story9/logout.html", context)

def story9_signup_page(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/story9/')
    else:
        form = SignUpForm()
    return render(request, 'story9/signup.html', {'form': form})

landing/templates/landing/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{{ page_title }}</title>

  </head>
  <body>
    <header>
        {% include 'landing/snippets/navbar.html' %}
    </header>
    
    {% block content %}

    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

landing/templates/landing/landing.html
{% extends 'landing/base.html' %}

{% block content %}
    <div class="text-center">
        <h1>Halo, apa kabar?!</h1>
    </div>
    
    <form method="POST" class="text-center">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" id="submit-button">Submit</button>
    </form>
    
    {% if not status %}
        <div class='d-flex justify-content-center mt-md-3'>
            <p>Mohon maaf, tidak ada Status yang dapat ditampilkan.</p>
        </div>
    {% else %}
        <div class='table-responsive col-md-6 mt-md-3 mx-auto'>
            <table class='table table-striped'>
                <thead class='thead-dark'>
                    <tr>
                        <th scope='col' class='align-middle'>#</th>
                        <th scope='col' class='align-middle'>Status</th>
                        <th scope='col' class='align-middle'>Tanggal/Waktu</th>
                    <tr>
                </thead>
                <tbody>
                    {% for obj in status %}
                        <tr>
                            <th scope='row' class='align-middle'>{{forloop.counter}}</th>
                            <td class='align-middle'>{{obj.status}}</th>
                            <td class='align-middle'>{{obj.date_created}}</th>
                        </tr>
                    {% endfor %}
                </tbody>
            <table>
        </div>
    {% endif %}
{% endblock content %}

landing/templates/landing/snippets/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" id="pacifico-font" href="#"><b>Salman's Story</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav pacifico-font">
    <a class="nav-item nav-link" id="pacifico-font" href="{% url 'landing:landing' %}">Story 6</a>
    <a class="nav-item nav-link" id="pacifico-font" href="{% url 'story7:story7' %}">Story 7</a>
    <a class="nav-item nav-link" id="pacifico-font" href="{% url 'story8:story8' %}">Story 8</a>
    <a class="nav-item nav-link" id="pacifico-font" href="{% url 'story9:story9' %}">Story 9</a>
  </div>
</nav>

story7/templates/story7/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" type="text/css" href="{% static 'story7/css/index.css' %}" />
        {% block stylesheet %}
        {% endblock stylesheet %}
        <title>
            {% block page_title %}
            {% endblock page_title %}
        </title>
    </head>
    <body>
        <header class="position-sticky sticky-top">
            {% include 'story7/snippets/navbar.html' %}
        </header>
        {% block content %}
        
        {% endblock content %}

        <script type="text/javascript" src="{% static 'story7/js/jquery-3.4.1.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'story7/js/index.js' %}"></script>
        {% block javascript %}
            
        {% endblock javascript %}
        
    </body>
</html>     

story7/templates/story7/index.html
{% extends 'story7/base.html' %}

{% load static %}

{% block page_title %}
    {{ title }}
{% endblock page_title %}

{% block content %}
    <div class="container my-4 mx-6" id="main-container">
        <div class="container d-flex justify-content-center" id="pacifico-font">
            <h1>Accordion - Story 7</h1>
        </div>    
        <section class="nav-wrap">
            <nav class="acnav" role="navigation">
                <ul class="acnav__list acnav__list--level1">
                    <li class="has-children">
                        <div class="acnav__label" id="kegiatan_header">
                            Kegiatan
                        </div>
                        <ul class="acnav__list acnav__list--level2">
                            {% if not kegiatan %}
                                <li>
                                    <p class="acnav__link acnav__link--level2" href="">No Nothing here</p>
                                </li>
                            {% else %}
                                {% for obj in kegiatan %}
                                    <li class="has-children">
                                        <div class="acnav__label acnav__label--level2">
                                            {{ obj.name }}
                                        </div>
                                        <ul class="acnav__list acnav__list--level3">
                                            <li>
                                                <div class="container">
                                                    <p>{{ obj.desc }}</p>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </li>

                    <li class="has-children">
                        <div class="acnav__label" id="organisasi_header">
                            Organisasi
                        </div>
                        <ul class="acnav__list acnav__list--level2">
                            {% if not organisasi %}
                                <li>
                                    <p class="acnav__link acnav__link--level2" href="">No Nothing here</p>
                                </li>
                            {% else %}
                                {% for obj in organisasi %}
                                    <li class="has-children">
                                        <div class="acnav__label acnav__label--level2">
                                            {{ obj.name }}
                                        </div>
                                        <ul class="acnav__list acnav__list--level3">
                                            <li>
                                                <div class="container text-justify">
                                                    <p><b>Date:</b> {{ obj.date }}</p>
                                                    <p><b>Position:</b> {{ obj.position }}</p>
                                                    <p><b>Description:</b> {{ obj.description }}</p>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </li>
                    <!-- start group 3 -->
                    <li class="has-children">
                        <div class="acnav__label" id="kepanitiaan_header">
                            Kepanitiaan
                        </div>
                        <ul class="acnav__list acnav__list--level2">
                            {% if not kepanitiaan %}
                                <li>
                                    <p class="acnav__link acnav__link--level2" href="">No Nothing here</p>
                                </li>
                            {% else %}
                                {% for obj in kepanitiaan %}
                                    <li class="has-children">
                                        <div class="acnav__label acnav__label--level2">
                                            {{ obj.name }}
                                        </div>
                                        <ul class="acnav__list acnav__list--level3">
                                            <li>
                                                <div class="container text-justify">
                                                    <p><b>Date:</b> {{ obj.date }}</p>
                                                    <p><b>Position:</b> {{ obj.position }}</p>
                                                    <p><b>Description:</b> {{ obj.description }}</p>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </li>	
                </ul>
            </nav>
        </section>
    </div>
{% endblock content %}

story7/templates/story7/snippets/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" id="pacifico-font" href="#"><b class="text-primary">Salman's Story</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav pacifico-font">
    <a class="nav-item nav-link text-secondary" id="pacifico-font" href="{% url 'landing:landing' %}">Story 6</a>
    <a class="nav-item nav-link text-secondary" id="pacifico-font" href="{% url 'story7:story7' %}">Story 7</a>
    <a class="nav-item nav-link text-secondary" id="pacifico-font" href="{% url 'story8:story8' %}">Story 8</a>
    <a class="nav-item nav-link text-secondary" id="pacifico-font" href="{% url 'story9:story9' %}">Story 9</a>
  </div>
    <div class="theme-switch-wrapper float-right">
        <label class="theme-switch" for="checkbox">
            <input type="checkbox" id="checkbox" />
            <div class="slider round" id="toggle-button"></div>
        </label>
        <em >Enable Dark Mode!</em>
    </div>
</nav>

story8/templates/story8/index.html
{% extends 'story7/base.html' %}
{% load static %}
{% block page_title %}
    {{ title }}
{% endblock page_title %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'story8/css/index8.css' %}" />
{% endblock stylesheet %}

{% block content %}
    <div class="container d-flex justify-content-center my-5" id="pacifico-font">
        <h1>AJAX - Story 8</h1>
    </div> 
    <div class="container d-flex justify-content-center">
        <form class="search">
            <input type="text" class="search-box" name="search-box" placeholder="What book are you looking for?">
            <button type="submit" class="search-button">
                <i class="fa fa-search"></i>    
            </button>
        </form>
    </div>
    <div class="container d-flex justify-content-center mt-5 mb-2" id="pacifico-font">
        <h4 class="no-books"></h4>
    </div>
    <div class="container d-flex justify-content-center">
        <table class="table no-books">
            <thead class="thead-custom">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Cover</th>
                    <th scope="col">Book Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Publisher</th>
                    <th scope="col">Pages</th>
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>     
    </div>
{% endblock content %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'story8/js/index8.js' %}"></script>
{% endblock javascript %}

story9/templates/story9/index9.html
{% extends 'story7/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="d-flex flex-column text-center justify-content-center align-align-middle">
            <p>You are logged in as {{ user }}</p>
            <a href="{% url "story9:story9_logout" %}"><button>Logout</button></a>
        </div>
    {% else %}
        <div class="d-flex flex-column text-center justify-content-center align-align-middle">
            <p>You are not logged as a User. You are currently browsing as {{ user }}</p>
            <p>Login?</p>
            <a href="{% url "story9:story9_login" %}"><button>Login</button></a>
        </div>
    {% endif %}
{% endblock content %}

story9/templates/story9/login.html
{% extends 'story7/base.html' %}

{% block content %}
    <div class="d-flex flex-column text-center justify-content-center align-align-middle">
        <a href="{% url "story9:story9" %}"><button type="">Home</button></a>
    {% if not user.is_authenticated %}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}    
            <button type="submit">Login</button>
        </form>
        <p>Don't have an account?</p>
        <a href="{% url "story9:story9_signup" %}"><button type="">Signup</button></a>
    {% endif %}
    </div>
{% endblock content %}

story9/templates/story9/logout.html
{% extends 'story7/base.html' %}

{% block content %}
    <ul>
        <li><a href="{% url "story9:story9" %}">Back</a></li>
    </ul>
    <p>Yakin mau logout?</p>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="logout" value="Logout">
    </form>
{% endblock content %}

story9/templates/story9/signup.html
{% extends 'story7/base.html' %}

{% block content %}
    <div class="d-flex flex-column">
        <a href="{% url "story9:story9" %}"><button type="">Home</button></a>
        <form method="POST">
            {% csrf_token %}
            <table class="table table-borderless">
                {% for field in form %}
                    <tr>
                        <td>{{ field.label_tag }}</td>
                        <td>{{ field }}</td>
                    </tr>
                {% endfor %}
            </table>
            <input type="submit" name="submit-button" value="Sign Up">
        </form>
    </div>
{% endblock content %}